### ISSUE TITLE
Bug: IOS device upgrade fails (false positive)

### ISSUE THREAD

**Issue by armartirosyan** [networktocode/pyntc#150]
The `install_os` method returns upgrade failure even thought the upgrade was successful:
```
>>> from pyntc.devices.ios_device import IOSDevice
>>> d = IOSDevice(host='192.168.1.100', username='admin', password='password')
>>> d.install_os('cat3k_caa-universalk9.16.12.01.SPA.bin')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/pyntc/devices/ios_device.py", line 295, in install_os
    raise OSInstallError(hostname=self.facts.get("hostname"), desired_boot=image_name)
pyntc.errors.OSInstallError: OSInstallError:
C3650-2 was unable to boot into cat3k_caa-universalk9.16.12.01.SPA.bin
>>> d.show('show version)
'\nC3650-2#show version\n
...TRIMMED...
Uptime for this control processor is 9 minutes\nSystem returned to ROM by Reload Command\nSystem image file is "flash:/cat3k_caa-universalk9.16.12.01.SPA.bin"\nLast reload reason: Reload Command\n\n\n\nC3650
...TRIMMED...'
```
**Fix**
```python
    def _wait_for_device_reboot(self, timeout=3600):
        start = time.time()
        while time.time() - start < timeout:
            try:
                self.open()
                self.show('show version')
                return
            except:  # noqa E722
                pass
```
**Environment**
```
Python - 3.8.5
Pip - 20.2.3
pyntc - 0.0.12
IOS - WS-C3650-48PQ
```

**Comment by jmcgill298** [comment]
#156
